## Reshaping tensors

In [2]:
import torch

In [2]:
t=torch.tensor([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("Original tensor:")
print(t)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
t_flat=t.flatten()
print("Flattened tensor:") 
print(t_flat)

Flattened tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


Flatten from Start Dimention

In [9]:
t_flat_start = torch.flatten(t, start_dim=0)
print("Flattened from start_dim=0:")
print(t_flat_start)
print(f"Shape: {t_flat_start.shape}")
print()

Flattened from start_dim=0:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([9])



In [27]:
t_3d = torch.tensor([[[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]]], dtype=torch.float32)
print("3D tensor:")
print(t_3d)
print(f"Shape: {t_3d.shape}")
print()

t_3d_flat = torch.flatten(t_3d, start_dim=2)
print("Flattened 3D tensor:")
print(t_3d_flat)
print(f"Shape: {t_3d_flat.shape}")

3D tensor:
tensor([[[[1., 2.],
          [3., 4.]],

         [[5., 6.],
          [7., 8.]]]])
Shape: torch.Size([1, 2, 2, 2])

Flattened 3D tensor:
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
Shape: torch.Size([1, 2, 4])


## Reshape: Change Shape

In [28]:
# Create a tensor
t = torch.tensor([[1, 2, 3, 4], 
                  [5, 6, 7, 8]], dtype=torch.float32)

print("Original tensor:")
print(t)
print(f"Shape: {t.shape} (2×4 = 8 elements)")
print()


Original tensor:
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
Shape: torch.Size([2, 4]) (2×4 = 8 elements)



In [30]:

# Reshape to 4×2
t_reshaped = t.reshape(4, 2)
print("Reshaped to (4, 2):")
print(t_reshaped)
print(f"Shape: {t_reshaped.shape} (4×2 = 8 elements)")
print()

# Reshape to 1D
t_1d = t.reshape(8)
print("Reshaped to 1D:")
print(t_1d)
print(f"Shape: {t_1d.shape}")
print()


Reshaped to (4, 2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
Shape: torch.Size([4, 2]) (4×2 = 8 elements)

Reshaped to 1D:
tensor([1., 2., 3., 4., 5., 6., 7., 8.])
Shape: torch.Size([8])



In [37]:

# Reshape with -1 (auto-calculate)
t_auto = t.reshape(-1)  # -1 means "figure it out"
print("Reshaped with -1:")
print(t_auto)
print(f"Shape: {t_auto.shape}")
print()


Reshaped with -1:
tensor([1., 2., 3., 4., 5., 6., 7., 8.])
Shape: torch.Size([8])



In [40]:

# Reshape 3D to 2D
t_3d = torch.arange(24).reshape(2, 3, 4)
print("3D tensor (2×3×4):")
print(t_3d)
print(f"Shape: {t_3d.shape}")
print()

t_2d_from_3d = t_3d.reshape(6, 4)
print("Reshaped to 2D (6×4):")
print(t_2d_from_3d)
print(f"Shape: {t_2d_from_3d.shape}")

3D tensor (2×3×4):
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])

Reshaped to 2D (6×4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])
Shape: torch.Size([6, 4])


In [41]:
t_3d = torch.arange(36).reshape(2, 3, 6)

print(t_3d)
print(f"Shape: {t_3d.shape}")
print()

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]])
Shape: torch.Size([2, 3, 6])



In [43]:
#create tenasor
t=torch.tensor([[1,2,3,4],
                     [5,6,7,8]],dtype=torch.float32)
print("Original tensor:")
print(t)
print(f"Shape: {t.shape}")
print() 


Original tensor:
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
Shape: torch.Size([2, 4])



In [46]:
t_view=t.view(4,2)
print(t_view)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


### View

In [47]:
# View shares memory with original
print("View shares memory:")
print(f"t[0, 0] = {t[0, 0]}")
print(f"t_view[0, 0] = {t_view[0, 0]}")
print()

# Modify view, original changes too!
t_view[0, 0] = 99
print("After modifying t_view[0, 0] = 99:")
print("Original t:")
print(t)
print("View t_view:")
print(t_view)
print("(Both changed - they share memory!)")
print()

# Reshape vs View
print("Difference:")
print("- reshape(): Works even if tensor is not contiguous (copies if needed)")
print("- view(): Requires contiguous tensor (faster, shares memory)")
print("- Both change shape without changing data")

View shares memory:
t[0, 0] = 1.0
t_view[0, 0] = 1.0

After modifying t_view[0, 0] = 99:
Original t:
tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]])
View t_view:
tensor([[99.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]])
(Both changed - they share memory!)

Difference:
- reshape(): Works even if tensor is not contiguous (copies if needed)
- view(): Requires contiguous tensor (faster, shares memory)
- Both change shape without changing data


## Squeeze: Remove Dimensions of Size 1
Squeeze removes dimensions with size 1! Useful for removing unnecessary dimensions.

In [52]:
t = torch.tensor([[[1, 2, 3]]], dtype=torch.float32)
print("Original tensor:")
print(t)
print(f"Shape: {t.shape}")
print()

Original tensor:
tensor([[[1., 2., 3.]]])
Shape: torch.Size([1, 1, 3])



In [57]:
# Squeeze all size-1 dimensions
t_squeezed = t.squeeze()
print("Squeezed (all size-1 dims removed):")
print(t_squeezed)
print(f"Shape: {t_squeezed.shape}")
print()

Squeezed (all size-1 dims removed):
tensor([1., 2., 3.])
Shape: torch.Size([3])



In [60]:
# Squeeze specific dimension
t2 = torch.tensor([[[1], [2], [3]]], dtype=torch.float32)
print("Another tensor:")
print(t2)
print(f"Shape: {t2.shape}")
print()

t2_squeezed_dim = t2.squeeze(dim=0)
print("Squeezed dimension 0:")
print(t2_squeezed_dim)
print(f"Shape: {t2_squeezed_dim.shape}")
print()

# Squeeze dimension 2
t2_squeezed_dim2 = t2.squeeze(dim=2)
print("Squeezed dimension 2:")
print(t2_squeezed_dim2)
print(f"Shape: {t2_squeezed_dim2.shape}")

Another tensor:
tensor([[[1.],
         [2.],
         [3.]]])
Shape: torch.Size([1, 3, 1])

Squeezed dimension 0:
tensor([[1.],
        [2.],
        [3.]])
Shape: torch.Size([3, 1])

Squeezed dimension 2:
tensor([[1., 2., 3.]])
Shape: torch.Size([1, 3])


## 5. Unsqueeze: Add Dimension of Size 1
Unsqueeze adds a new dimension of size 1! Useful for adding batch dimension or matching shapes.

In [5]:
t = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)
print(t,t.shape)
t_unsqueze= t.unsqueeze(0)
print(t_unsqueze,t_unsqueze.shape)
t_unsqueze_dim1 = t.unsqueeze(dim=1)
print(t_unsqueze_dim1,t_unsqueze_dim1.shape)
t_unsqueeeze_dim2 = t.unsqueeze(dim=-1)
print(t_unsqueeeze_dim2,t_unsqueeeze_dim2.shape)

tensor([[1., 2., 3., 4.]]) torch.Size([1, 4])
tensor([[[1., 2., 3., 4.]]]) torch.Size([1, 1, 4])
tensor([[[1., 2., 3., 4.]]]) torch.Size([1, 1, 4])
tensor([[[1.],
         [2.],
         [3.],
         [4.]]]) torch.Size([1, 4, 1])


In [6]:
t.ndim

2

In [7]:
# Create a tensor
t = torch.tensor([[1, 2, 3, 4], 
                  [5, 6, 7, 8]], dtype=torch.float32)

print("Original tensor:")
print(t)
print(f"Shape: {t.shape}")
print()

print("=" * 60)
print("FLATTEN:")
print("=" * 60)
t_flat = t.flatten()
print(f"t.flatten(): {t_flat.shape}")
print()

print("=" * 60)
print("RESHAPE:")
print("=" * 60)
t_reshaped = t.reshape(4, 2)
print(f"t.reshape(4, 2): {t_reshaped.shape}")
t_reshaped2 = t.reshape(8)
print(f"t.reshape(8): {t_reshaped2.shape}")
print()

print("=" * 60)
print("VIEW:")
print("=" * 60)
t_view = t.view(4, 2)
print(f"t.view(4, 2): {t_view.shape}")
print("(Shares memory with original)")
print()

print("=" * 60)
print("SQUEEZE:")
print("=" * 60)
t_with_ones = torch.tensor([[[1, 2, 3]]], dtype=torch.float32)
print(f"Original: {t_with_ones.shape}")
t_squeezed = t_with_ones.squeeze()
print(f"t.squeeze(): {t_squeezed.shape}")
print()

print("=" * 60)
print("UNSQUEEZE:")
print("=" * 60)
t_1d = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(f"Original: {t_1d.shape}")
t_unsqueezed = t_1d.unsqueeze(0)
print(f"t.unsqueeze(0): {t_unsqueezed.shape}")
print()

print("=" * 60)
print("SUMMARY:")
print("=" * 60)
print("flatten(): Make 1D")
print("reshape(): Change shape (may copy)")
print("view(): Change shape (shares memory, faster)")
print("squeeze(): Remove size-1 dimensions")
print("unsqueeze(): Add size-1 dimension")

Original tensor:
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
Shape: torch.Size([2, 4])

FLATTEN:
t.flatten(): torch.Size([8])

RESHAPE:
t.reshape(4, 2): torch.Size([4, 2])
t.reshape(8): torch.Size([8])

VIEW:
t.view(4, 2): torch.Size([4, 2])
(Shares memory with original)

SQUEEZE:
Original: torch.Size([1, 1, 3])
t.squeeze(): torch.Size([3])

UNSQUEEZE:
Original: torch.Size([4])
t.unsqueeze(0): torch.Size([1, 4])

SUMMARY:
flatten(): Make 1D
reshape(): Change shape (may copy)
view(): Change shape (shares memory, faster)
squeeze(): Remove size-1 dimensions
unsqueeze(): Add size-1 dimension


# randopm tyensors

In [14]:
random_tensor = torch.rand(2, 3)
print("Random tensor: \n",random_tensor)


Random tensor: 
 tensor([[0.6993, 0.0822, 0.1398],
        [0.9002, 0.2412, 0.9955]])


In [19]:
random_int= torch.randint(0, 14, (2, 3))
print("Random integer tensor: \n", random_int)

Random integer tensor: 
 tensor([[ 9,  8,  6],
        [ 7, 13,  4]])


In [23]:
random_norm= torch.randn(3, 9)
print("Random normal tensor: \n", random_norm)

Random normal tensor: 
 tensor([[-1.5633,  0.6853,  1.0524,  0.7282, -1.2296,  0.4471, -0.5439,  0.2502,
         -0.7465],
        [ 0.7666,  1.8687, -1.7668,  0.4080,  1.5586, -1.1379,  0.6064,  0.4309,
         -1.2002],
        [ 0.4571, -0.9547,  0.4255, -0.5567,  0.4155,  0.7613, -0.1820, -0.0625,
         -0.1978]])


In [29]:
random_range= torch.rand(3, 5) * 10
print("Random range tensor: \n", random_range)

Random range tensor: 
 tensor([[7.5869, 1.0782, 8.2495, 3.9746, 8.2326],
        [6.6008, 3.7253, 7.1321, 7.4009, 2.0703],
        [6.2541, 7.5237, 7.0334, 1.3402, 6.0648]])
