## Concatenating Tensors: cat and stack
Combine multiple tensors together! cat concatenates along existing dimension, stack creates new dimension.

In [1]:
import torch

In [3]:
# Create two tensors
t1 = torch.tensor([[1, 2], 
                   [3, 4]], dtype=torch.float32)

t2 = torch.tensor([[5, 6], 
                   [7, 8]], dtype=torch.float32)
print(t1, t1.shape, "\n", t2, t2.shape)

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2]) 
 tensor([[5., 6.],
        [7., 8.]]) torch.Size([2, 2])


In [5]:
t_cat0 = torch.cat([t1, t2], dim=0)
print(t_cat0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [12]:
t_cat1 = torch.cat([t1, t2], dim=1)
print(t_cat1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## stack: Stack Along New Dimension
torch.stack() creates a new dimension and stacks tensors! All tensors must have the same shape.

In [7]:
t_stack0 = torch.stack([t1, t2], dim=0)
print(t_stack0)
print(f"Shape: {t_stack0.shape}")

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
Shape: torch.Size([2, 2, 2])


In [8]:
t_stack1 = torch.stack([t1, t2], dim=1)
print(t_stack1)
print(f"Shape: {t_stack1.shape}")

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])
Shape: torch.Size([2, 2, 2])


In [9]:
# Stack along dimension 2
t_stack2 = torch.stack([t1, t2], dim=2)
print("torch.stack([t1, t2], dim=2):")
print(t_stack2)
print(f"Shape: {t_stack2.shape}")
print()

torch.stack([t1, t2], dim=2):
tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])
Shape: torch.Size([2, 2, 2])



In [10]:
# Compare: cat vs stack
print("=" * 60)
print("COMPARISON: cat vs stack")
print("=" * 60)
print("cat: Concatenates along existing dimension")
print(f"  cat shape: {torch.cat([t1, t2], dim=0).shape}")
print()
print("stack: Creates new dimension and stacks")
print(f"  stack shape: {torch.stack([t1, t2], dim=0).shape}")
print()
print("Difference: stack adds a new dimension!")

COMPARISON: cat vs stack
cat: Concatenates along existing dimension
  cat shape: torch.Size([4, 2])

stack: Creates new dimension and stacks
  stack shape: torch.Size([2, 2, 2])

Difference: stack adds a new dimension!


## Key Takeaways
Concatenating tensors:

torch.cat([t1, t2, ...], dim=d) - concatenate along dimension d
torch.stack([t1, t2, ...], dim=d) - stack along new dimension d
Key differences:

cat: Concatenates along existing dimension (tensors must match except along dim)
stack: Creates new dimension and stacks (all tensors must have same shape)
Common use cases:

cat: Combine features, merge batches, concatenate layers
stack: Create batch dimension, sequence dimension, stack channels
Remember: cat expands existing dimension, stack creates new dimension!