import torch

In [1]:
import torch

## 1. Basic Indexing
Access single elements using indices! Indexing starts at 0.

In [6]:
# Create a 2D tensor
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float32)

print("Tensor t:")
print(t)
print(f"Shape: {t.shape}")
print()


Tensor t:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Shape: torch.Size([3, 3])



In [7]:

# Access single element
print("Accessing elements:")
print(f"t[0, 0] = {t[0, 0]}  (first row, first column)")
print(f"t[0, 1] = {t[0, 1]}  (first row, second column)")
print(f"t[1, 0] = {t[1, 0]}  (second row, first column)")
print(f"t[2, 2] = {t[2, 2]}  (third row, third column)")
print()

# Access entire row
print("Accessing rows:")
print(f"t[0] = {t[0]}  (first row)")
print(f"t[1] = {t[1]}  (second row)")
print()

# Access entire column (using slicing)
print("Accessing columns:")
print(f"t[:, 0] = {t[:, 0]}  (first column)")
print(f"t[:, 1] = {t[:, 1]}  (second column)")

Accessing elements:
t[0, 0] = 1.0  (first row, first column)
t[0, 1] = 2.0  (first row, second column)
t[1, 0] = 4.0  (second row, first column)
t[2, 2] = 9.0  (third row, third column)

Accessing rows:
t[0] = tensor([1., 2., 3.])  (first row)
t[1] = tensor([4., 5., 6.])  (second row)

Accessing columns:
t[:, 0] = tensor([1., 4., 7.])  (first column)
t[:, 1] = tensor([2., 5., 8.])  (second column)


## 2. Slicing: Get Ranges
Use slicing to get ranges of elements! Syntax: [start:end:step]

In [8]:
# Create a tensor
t = torch.tensor([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]], dtype=torch.float32)

print("Tensor t:")
print(t)
print(t.shape)


Tensor t:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
torch.Size([3, 4])


In [ ]:

# Slicing rows
print("Slicing rows:")
print(f"t[0:2] = (first 2 rows)")
print(t[0:2])
print()

print(f"t[1:] = (from row 1 to end)")
print(t[1:])
print()

print(f"t[:2] = (first 2 rows)")
print(t[:2])
print()

# Slicing columns
print("Slicing columns:")
print(f"t[:, 0:2] = (first 2 columns)")
print(t[:, 0:2])
print()

print(f"t[:, 2:] = (from column 2 to end)")
print(t[:, 2:])
print()

# Slicing both rows and columns
print("Slicing rows and columns:")
print(f"t[0:2, 1:3] = (rows 0-1, columns 1-2)")
print(t[0:2, 1:3])

Slicing rows:
t[0:2] = (first 2 rows)
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

t[1:] = (from row 1 to end)
tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

t[:2] = (first 2 rows)
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

Slicing columns:
t[:, 0:2] = (first 2 columns)
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

t[:, 2:] = (from column 2 to end)
tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])

Slicing rows and columns:
t[0:2, 1:3] = (rows 0-1, columns 1-2)
tensor([[2., 3.],
        [6., 7.]])


## conditional

In [11]:
# Create a tensor
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float32)

print("Tensor t:")
print(t)
print()

# Index with list
print("Indexing with list:")
indices = [0, 2]
print(f"t[indices] = t[[0, 2]] (rows 0 and 2)")
print(t[indices])
print()

# Boolean masking
print("Boolean masking:")
mask = t > 5
print(f"mask = t > 5")
print(mask)
print()

print("t[mask] (elements where mask is True):")
print(t[t > 5])
print()

# Conditional indexing
print("Conditional indexing:")
print(f"t[t > 5] = {t[t > 5]}")
print(f"t[t % 2 == 0] = {t[t % 2 == 0]}  (even numbers)")

Tensor t:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Indexing with list:
t[indices] = t[[0, 2]] (rows 0 and 2)
tensor([[1., 2., 3.],
        [7., 8., 9.]])

Boolean masking:
mask = t > 5
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

t[mask] (elements where mask is True):
tensor([6., 7., 8., 9.])

Conditional indexing:
t[t > 5] = tensor([6., 7., 8., 9.])
t[t % 2 == 0] = tensor([2., 4., 6., 8.])  (even numbers)


## 4. Modifying Values with Indexing
Change values using indexing! Very useful for updating specific elements."

In [13]:
# Create a tensor
t = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], dtype=torch.float32)

print("Original tensor:")
print(t)
print()

# Modify single element
t[0, 0] = 99
print("After t[0, 0] = 99:")
print(t)
print()

# Modify entire row
t[1] = torch.tensor([10, 20, 30], dtype=torch.float32)
print("After t[1] = [10, 20, 30]:")
print(t)
print()

# Modify slice
t[0:2, 0:2] = torch.tensor([[100, 200], 
                            [300, 400]], dtype=torch.float32)
print("After modifying slice t[0:2, 0:2]:")
print(t)
print()

# Modify with boolean mask
t[t > 50] = 0
print("After t[t > 50] = 0:")
print(t)

Original tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

After t[0, 0] = 99:
tensor([[99.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

After t[1] = [10, 20, 30]:
tensor([[99.,  2.,  3.],
        [10., 20., 30.],
        [ 7.,  8.,  9.]])

After modifying slice t[0:2, 0:2]:
tensor([[100., 200.,   3.],
        [300., 400.,  30.],
        [  7.,   8.,   9.]])

After t[t > 50] = 0:
tensor([[ 0.,  0.,  3.],
        [ 0.,  0., 30.],
        [ 7.,  8.,  9.]])


##  Key Takeaways
Indexing:

tensor[i, j] - access element at position (i, j)
tensor[i] - access row i
tensor[:, j] - access column j
Slicing:

tensor[start:end] - slice from start to end
tensor[start:end:step] - slice with step
tensor[:] - all elements
Advanced:

tensor[indices] - index with list
tensor[mask] - boolean masking
tensor[condition] - conditional indexing
Modifying:

tensor[i, j] = value - modify element
tensor[mask] = value - modify based on mask
Remember: Indexing starts at 0, and you can use it to read or modify values!