## Special Tensors: eye, rand, arange, linspace
Create special tensors for common use cases! Identity matrices, random values, sequences, and more.

In [2]:

import torch

In [3]:

# Create identity matrix
I = torch.eye(3)
print("Identity matrix (3×3):")
print(I)
print(f"Shape: {I.shape}")
print()

# Identity matrix with different dtype
I_float = torch.eye(3, dtype=torch.float32)
print("Identity matrix (float32):")
print(I_float)
print(f"dtype: {I_float.dtype}")
print()

# Non-square identity (rectangular)
I_rect = torch.eye(2, 3)
print("Rectangular identity (2×3):")
print(I_rect)
print(f"Shape: {I_rect.shape}")
print()


Identity matrix (3×3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Shape: torch.Size([3, 3])

Identity matrix (float32):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
dtype: torch.float32

Rectangular identity (2×3):
tensor([[1., 0., 0.],
        [0., 1., 0.]])
Shape: torch.Size([2, 3])



In [4]:
A = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.float32)
I_3x3 = torch.eye(3, dtype=torch.float32)

result = A @ I_3x3
print("Matrix multiplication with identity:")
print(f"A:")
print(A)
print(f"I:")
print(I_3x3)
print(f"A @ I:")
print(result)
print(f"(Should equal A: {torch.equal(A, result)})")

Matrix multiplication with identity:
A:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
I:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
A @ I:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
(Should equal A: True)


## rand: Random Values
torch.rand() creates tensors with random values between 0 and 1! Useful for initializing neural networks.

In [5]:
# Random values between 0 and 1
random_tensor = torch.rand(3, 4)
print("Random tensor (values between 0 and 1):")
print(random_tensor)
print(f"Shape: {random_tensor.shape}")
print()

# Random values with specific range
random_range = torch.rand(2, 3) * 10  # Scale to 0-10
print("Random values scaled to 0-10:")
print(random_range)
print()

# Random integers
random_int = torch.randint(0, 10, (3, 4))
print("Random integers (0 to 9):")
print(random_int)
print(f"Shape: {random_int.shape}")
print()

# Random from normal distribution (mean=0, std=1)
normal_tensor = torch.randn(3, 4)
print("Random from normal distribution:")
print(normal_tensor)
print(f"Mean: {normal_tensor.mean():.3f}")
print(f"Std: {normal_tensor.std():.3f}")
print()

# Random with specific seed (for reproducibility)
torch.manual_seed(42)
random_seed = torch.rand(2, 3)
print("Random with seed=42:")
print(random_seed)
print("(Same seed = same random values!)")


Random tensor (values between 0 and 1):
tensor([[0.7945, 0.4112, 0.7870, 0.9963],
        [0.9922, 0.7688, 0.9246, 0.5627],
        [0.2552, 0.7272, 0.7483, 0.1771]])
Shape: torch.Size([3, 4])

Random values scaled to 0-10:
tensor([[3.1024, 5.2774, 5.3457],
        [1.2541, 2.3180, 1.5019]])

Random integers (0 to 9):
tensor([[2, 2, 0, 7],
        [7, 5, 8, 1],
        [6, 6, 8, 1]])
Shape: torch.Size([3, 4])

Random from normal distribution:
tensor([[ 1.5866, -0.6179,  0.0198,  0.1294],
        [ 0.0722, -1.4643, -0.2955, -0.5489],
        [ 0.1446,  1.4846, -0.3372,  0.7893]])
Mean: 0.080
Std: 0.871

Random with seed=42:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
(Same seed = same random values!)


## sequence

In [6]:
# Create sequence from 0 to 9
seq1 = torch.arange(10)
print("torch.arange(10):")
print(seq1)
print()

# Create sequence with start and end
seq2 = torch.arange(2, 8)
print("torch.arange(2, 8):")
print(seq2)
print()

# Create sequence with step
seq3 = torch.arange(0, 10, 2)
print("torch.arange(0, 10, 2) - step=2:")
print(seq3)
print()

# Create sequence with float values
seq4 = torch.arange(0.0, 5.0, 0.5)
print("torch.arange(0.0, 5.0, 0.5) - float step:")
print(seq4)
print()

# Create sequence with specific dtype
seq5 = torch.arange(10, dtype=torch.float32)
print("torch.arange(10, dtype=torch.float32):")
print(seq5)
print(f"dtype: {seq5.dtype}")
print()

# Reshape arange to 2D
seq_2d = torch.arange(12).reshape(3, 4)
print("arange(12) reshaped to (3, 4):")
print(seq_2d)


torch.arange(10):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.arange(2, 8):
tensor([2, 3, 4, 5, 6, 7])

torch.arange(0, 10, 2) - step=2:
tensor([0, 2, 4, 6, 8])

torch.arange(0.0, 5.0, 0.5) - float step:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000])

torch.arange(10, dtype=torch.float32):
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
dtype: torch.float32

arange(12) reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## linspace: Linear Spacing
torch.linspace() creates evenly spaced values in a range! Specify start, end, and number of points.

In [ ]:
lin1=torch.linspace(0,1,5) # Create 5 evenly spaced values from 0 to 1
print(lin1)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [11]:
lin2=torch.linspace(0,10,5) # Create 5 evenly spaced values from 0 to 10
print(lin2)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [15]:
lin3=torch.linspace(-5,5,11) # Create 11 evenly spaced values from -5 to 5
print(lin3)

tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])


In [16]:
# Compare: arange vs linspace
print("=" * 60)
print("COMPARISON: arange vs linspace")
print("=" * 60)
print("arange: Specify step size")
arange_ex = torch.arange(0, 10, 2)
print(f"  torch.arange(0, 10, 2): {arange_ex}")
print()

print("linspace: Specify number of points")
linspace_ex = torch.linspace(0, 8, 5)
print(f"  torch.linspace(0, 8, 5): {linspace_ex}")
print()

print("Difference:")
print("  - arange: You control the step")
print("  - linspace: You control the number of points")

     

COMPARISON: arange vs linspace
arange: Specify step size
  torch.arange(0, 10, 2): tensor([0, 2, 4, 6, 8])

linspace: Specify number of points
  torch.linspace(0, 8, 5): tensor([0., 2., 4., 6., 8.])

Difference:
  - arange: You control the step
  - linspace: You control the number of points


## Other Special Tensor Functions
Let's see more useful tensor creation functions!

In [17]:
# ones: Tensor filled with ones
ones = torch.ones(3, 4)
print("torch.ones(3, 4):")
print(ones)
print()

# zeros: Tensor filled with zeros
zeros = torch.zeros(3, 4)
print("torch.zeros(3, 4):")
print(zeros)
print()

# full: Tensor filled with specific value
full = torch.full((3, 4), 5.0)
print("torch.full((3, 4), 5.0):")
print(full)
print()

# empty: Uninitialized tensor (contains garbage values)
empty = torch.empty(3, 4)
print("torch.empty(3, 4) - uninitialized:")
print(empty)
print("(Values are random/garbage - be careful!)")
print()

# Summary
print("=" * 60)
print("SUMMARY OF SPECIAL TENSORS")
print("=" * 60)
print("torch.eye(n) - identity matrix")
print("torch.rand(shape) - random values (0-1)")
print("torch.randn(shape) - random from normal distribution")
print("torch.randint(low, high, shape) - random integers")
print("torch.arange(start, end, step) - sequence with step")
print("torch.linspace(start, end, steps) - evenly spaced values")
print("torch.ones(shape) - filled with ones")
print("torch.zeros(shape) - filled with zeros")
print("torch.full(shape, value) - filled with specific value")
print("torch.empty(shape) - uninitialized (garbage values)")

     

torch.ones(3, 4):
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.zeros(3, 4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.full((3, 4), 5.0):
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

torch.empty(3, 4) - uninitialized:
tensor([[8.5823e-24, 0.0000e+00, 8.4802e-24, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
        [8.6632e-24, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
(Values are random/garbage - be careful!)

SUMMARY OF SPECIAL TENSORS
torch.eye(n) - identity matrix
torch.rand(shape) - random values (0-1)
torch.randn(shape) - random from normal distribution
torch.randint(low, high, shape) - random integers
torch.arange(start, end, step) - sequence with step
torch.linspace(start, end, steps) - evenly spaced values
torch.ones(shape) - filled with ones
torch.zeros(shape) - filled with zeros
torch.full(shape, value) - filled with specific value
torch