## 1. Creating Tensors in PyTorch
Tensors are like arrays in NumPy, but designed for deep learning! They can store numbers and perform operations efficiently on GPUs.
\
using colab CPU

In [1]:
import torch
import numpy as np

In [2]:
t1=torch.tensor([1,2,3,4,5,6]) #1d tensor
t2=torch.tensor([[1,2,3],[4,5,6]]) #2d tensor
t3=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]]) #3d tensor
print(t1)
print(t2)
print(t3)


tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## 2. Creating Tensors with Zeros and Ones
Create tensors filled with zeros or ones of a specific shape!

In [9]:
zeros_1d=torch.zeros(5)
print(zeros_1d)
zeros_2d = torch.zeros(3, 4)
print(zeros_2d)


tensor([0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
# Create tensor filled with ones
ones_1d = torch.ones(5)
print("1D tensor of ones:")
print(ones_1d)
print()

ones_2d = torch.ones(2, 3)
print("2D tensor of ones (2 rows, 3 columns):")
print(ones_2d)
print()

# Create tensor with specific value
full_tensor = torch.full((2, 3), 5.0)
print("2D tensor filled with 5.0:")
print(full_tensor)

1D tensor of ones:
tensor([1., 1., 1., 1., 1.])

2D tensor of ones (2 rows, 3 columns):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

2D tensor filled with 5.0:
tensor([[5., 5., 5.],
        [5., 5., 5.]])


## tensors with NumPy

In [11]:
np_array=np.array([1,2,3,4,5,6])
print(np_array)

#convert to tensor
torch_tensor=torch.from_numpy(np_array)
print(torch_tensor)

#convert pytorch to numpy
back_to_np=torch_tensor.numpy()
print(back_to_np)

[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6])
[1 2 3 4 5 6]


<b>Note: They share memory if using from_numpy()!</b>
<p>

("Note: torch.from_numpy() shares memory with NumPy array!")
\
("Changes to one affect the other (unless you use .clone())")

## Creating Tensors with Random Values
Generate random tensors for initializing neural networks!

In [12]:
#random tensor
random_tensor=torch.rand(3,5)
print(random_tensor)

tensor([[0.2909, 0.6329, 0.8302, 0.0104, 0.9299],
        [0.2675, 0.4538, 0.9203, 0.4078, 0.2646],
        [0.6970, 0.8564, 0.9101, 0.5656, 0.2292]])


In [13]:
# random int
random_int=torch.randint(low=0,high=10,size=(3,3))
print(random_int)

tensor([[4, 0, 1],
        [6, 0, 1],
        [3, 6, 9]])


In [16]:
print("random value normal")
# random value from normal distribution
normal_tensor=torch.randn(3,3)
print(normal_tensor)


print("random value with specific range")
# Random values with specific range
random_range = torch.rand(3, 4) * 10  # Scale to 0-10
print("Random values scaled to 0-10:")
print(random_range)

# for specific range
# scaled=rand∗(max−min)+min
specific_range = torch.rand(3, 4) * (20 - 5) + 5  # Scale to 5-20
print("Random values scaled to 5-20:")
print(specific_range)

random value normal
tensor([[-0.0682, -0.5880,  0.3990],
        [ 0.6862,  1.8477, -1.3504],
        [-0.0663,  1.1003, -0.9636]])
random value with specific range
Random values scaled to 0-10:
tensor([[0.2208, 0.1475, 9.8110, 8.6128],
        [4.2885, 4.1442, 2.0099, 8.0397],
        [1.7689, 2.9351, 6.7603, 9.4184]])
Random values scaled to 5-20:
tensor([[19.0573,  6.3601, 19.5064, 11.9848],
        [ 5.8696, 13.0305, 15.5650,  9.1127],
        [ 7.3275,  9.0888, 15.1782,  7.1273]])


## Data Types (dtype)
Tensors can have different data types: float32, int64, etc. Specify the type when creating tensors!

In [17]:
# Default float tensor
t_float = torch.tensor([1.0, 2.0, 3.0])
print("Float tensor (default):")
print(t_float)
print(f"dtype: {t_float.dtype}")
print()

# Integer tensor
t_int = torch.tensor([1, 2, 3], dtype=torch.int64)
print("Integer tensor:")
print(t_int)
print(f"dtype: {t_int.dtype}")
print()

# Float32 tensor (most common for neural networks)
t_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float32 tensor:")
print(t_float32)
print(f"dtype: {t_float32.dtype}")
print()

# Convert between types
t_convert = torch.tensor([1, 2, 3], dtype=torch.int64)
t_float_converted = t_convert.float()
print("Converted to float:")
print(t_float_converted)
print(f"dtype: {t_float_converted.dtype}")
print()

# Common dtypes
print("Common dtypes:")
print(f"torch.float32 (or torch.float): 32-bit float")
print(f"torch.float64 (or torch.double): 64-bit float")
print(f"torch.int32 (or torch.int): 32-bit integer")
print(f"torch.int64 (or torch.long): 64-bit integer")


Float tensor (default):
tensor([1., 2., 3.])
dtype: torch.float32

Integer tensor:
tensor([1, 2, 3])
dtype: torch.int64

Float32 tensor:
tensor([1., 2., 3.])
dtype: torch.float32

Converted to float:
tensor([1., 2., 3.])
dtype: torch.float32

Common dtypes:
torch.float32 (or torch.float): 32-bit float
torch.float64 (or torch.double): 64-bit float
torch.int32 (or torch.int): 32-bit integer
torch.int64 (or torch.long): 64-bit integer


# Matrix Multiplication

## Matrix Multiplication (@ operator)

In [18]:
# Create two matrices
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B:")
print(B)
print(f"Shape: {B.shape}")
print()

# Matrix multiplication using @
result = A @ B
print("A @ B (matrix multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# Using torch.matmul()
result2 = torch.matmul(A, B)
print("torch.matmul(A, B):")
print(result2)
print("(Same result!)")


Matrix A:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])
Shape: torch.Size([2, 2])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
Shape: torch.Size([2, 2])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
(Same result!)


## Matrix-Vector Multiplication

In [20]:
# Matrix-vector multiplication
M = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

v = torch.tensor([5, 6], dtype=torch.float32)

print("Matrix M:")
print(M)
print(f"Shape: {M.shape}")
print()

print("Vector v:")
print(v)
print(f"Shape: {v.shape}")
print()

# Matrix × Vector
result = M @ v
print("M @ v (matrix-vector multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# How it works
print("How it works:")
print(f"Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = {M[0, 0]}*{v[0]} + {M[0, 1]}*{v[1]} = {result[0]}")
print(f"Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = {M[1, 0]}*{v[0]} + {M[1, 1]}*{v[1]} = {result[1]}")


Matrix M:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Vector v:
tensor([5., 6.])
Shape: torch.Size([2])

M @ v (matrix-vector multiplication):
tensor([17., 39.])
Shape: torch.Size([2])

How it works:
Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = 1.0*5.0 + 2.0*6.0 = 17.0
Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = 3.0*5.0 + 4.0*6.0 = 39.0


## Batch Matrix Multiplication
Process multiple matrices at once using batch dimensions! Very useful for neural networks!

In [21]:
# Batch matrix multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

print("Batch A (3 matrices, each 2×4):")
print(batch_A)
print(f"Shape: {batch_A.shape}")
print()

print("Batch B (3 matrices, each 4×3):")
print(batch_B)
print(f"Shape: {batch_B.shape}")
print()

# Batch matrix multiplication
batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

# Verify: first matrix multiplication
A0 = batch_A[0]
B0 = batch_B[0]
result0 = A0 @ B0

print("First matrix multiplication (manual):")
print(result0)
print()

print("First matrix multiplication (from batch):")
print(batch_result[0])
print("(Should match!)")
print(f"Are they equal? {torch.allclose(result0, batch_result[0])}")


Batch A (3 matrices, each 2×4):
tensor([[[-0.1375, -1.9046, -1.8223, -0.5429],
         [-0.8322,  1.3560, -1.7003,  1.0033]],

        [[ 0.5620,  0.1580,  1.3921, -0.1218],
         [-0.9813,  1.3131,  1.1187, -0.1872]],

        [[-2.1809,  1.4688,  0.2761,  1.4994],
         [-1.0565,  0.3903, -0.0615,  0.7492]]])
Shape: torch.Size([3, 2, 4])

Batch B (3 matrices, each 4×3):
tensor([[[ 0.8027, -0.8815, -2.6656],
         [ 0.1778, -0.5842, -0.6582],
         [ 0.6936,  1.4486,  0.9531],
         [ 0.2161,  1.1313,  0.5179]],

        [[ 0.3674,  0.3418, -0.4018],
         [-1.2995,  0.1525, -1.4352],
         [ 0.1169,  0.5422, -1.1829],
         [ 0.5120,  0.8626,  0.5193]],

        [[-1.1004, -1.9757,  0.8468],
         [ 2.4984,  0.6471,  0.5968],
         [-0.8340, -0.7895, -1.0088],
         [-0.3583,  1.1808,  0.5920]]])
Shape: torch.Size([3, 4, 3])

Batch matrix multiplication result:
tensor([[[-1.8301, -2.0202, -0.3979],
         [-1.3894, -1.3865,  0.2248]],

        [[ 0

## Element-wise Multiplication
Multiply elements at the same position (not matrix multiplication)! Use * for element-wise multiplication.

In [22]:
# Element-wise multiplication (different from matrix multiplication!)
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

# Element-wise multiplication
element_wise = A * B
print("A * B (element-wise multiplication):")
print(element_wise)
print()

# Matrix multiplication (for comparison)
matrix_mult = A @ B
print("A @ B (matrix multiplication):")
print(matrix_mult)
print()

print("Notice: Element-wise (*) is different from matrix multiplication (@)!")
print(f"Element-wise: {A[0, 0]} * {B[0, 0]} = {element_wise[0, 0]}")
print(f"Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = {matrix_mult[0, 0]}")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

A * B (element-wise multiplication):
tensor([[ 5., 12.],
        [21., 32.]])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])

Notice: Element-wise (*) is different from matrix multiplication (@)!
Element-wise: 1.0 * 5.0 = 5.0
Matrix mult: A[0, 0]*B[0, 0] + A[0, 1]*B[1, 0] = 19.0


##  Transposing Tensors in PyTorch
Transpose flips rows and columns! Very useful for matrix operations and neural networks.

In [2]:
A=torch.tensor([[1,2,3],
                 [4,5,6]])
print(A)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
A_transpose=A.T
A_transpose1=A.t()
print(A_transpose)
print(A_transpose1)
print(A_transpose.shape)
print(A_transpose1.shape)
print(A.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])


## Transposing Higher-Dimensional Tensors

In [9]:
# Create a 3D tensor
t = torch.tensor([[[1, 2,11], 
                   [3, 4,12]], 
                  [[5, 6, 13], 
                   [7, 8,14]]], dtype=torch.float32)

print("Original 3D tensor:")
print(t)
print(f"Shape: {t.shape}")
print()




Original 3D tensor:
tensor([[[ 1.,  2., 11.],
         [ 3.,  4., 12.]],

        [[ 5.,  6., 13.],
         [ 7.,  8., 14.]]])
Shape: torch.Size([2, 2, 3])



In [10]:
# Transpose specific dimensions
# transpose(dim0, dim1) swaps dim0 and dim1
t_transposed = torch.transpose(t, 0, 1)
print("Transposed (swapped dimension 0 and 2):")
print(t_transposed)
print(f"Shape: {t_transposed.shape}")
print()

# 

Transposed (swapped dimension 0 and 2):
tensor([[[ 1.,  2., 11.],
         [ 5.,  6., 13.]],

        [[ 3.,  4., 12.],
         [ 7.,  8., 14.]]])
Shape: torch.Size([2, 2, 3])



In [11]:
t_permuted=t.permute(2, 0, 1)
print("Permuted (new order of dimensions):")
print(t_permuted)
print(f"Shape: {t_permuted.shape}") 

Permuted (new order of dimensions):
tensor([[[ 1.,  3.],
         [ 5.,  7.]],

        [[ 2.,  4.],
         [ 6.,  8.]],

        [[11., 12.],
         [13., 14.]]])
Shape: torch.Size([3, 2, 2])


permute(2, 0, 1) means:
"new dim 0 = old dim 2
 new dim 1 = old dim 0
 new dim 2 = old dim 1"

Before:  dim0=2  dim1=2  dim2=3
              ↓       ↓      ↓
After:   dim0=3  dim1=2  dim2=2
         (old2) (old0) (old1)

## Common Operation

In [29]:
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print()

print("Matrix B:")
print(B)
print()

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])



In [30]:
# (A @ B).T = B.T @ A.T (property of transpose)
AB = A @ B
AB_transpose = AB.T

BTA = B.T @ A.T

print("(A @ B).T:")
print(AB_transpose)
print()

(A @ B).T:
tensor([[19., 43.],
        [22., 50.]])



In [31]:
print("B.T @ A.T:")
print(BTA)
print()

print("Are they equal? (Should be!)")
print(torch.allclose(AB_transpose, BTA))
print()

B.T @ A.T:
tensor([[19., 43.],
        [22., 50.]])

Are they equal? (Should be!)
True



In [33]:
# Transpose of transpose = original
print("Transpose of transpose:")
print("(A.T).T:")
print(A.T.T)
print()
print("Original A:")
print(A)
print(f"Are they equal? {torch.equal(A.T.T, A)}")


Transpose of transpose:
(A.T).T:
tensor([[1., 2.],
        [3., 4.]])

Original A:
tensor([[1., 2.],
        [3., 4.]])
Are they equal? True
